services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: afno_site
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-service:
    build:
      context: .
      dockerfile: ./apps/product-service/src/Dockerfile
      target: development
    command: pnpm run start:debug product-service
    ports:
      - '3004:3004'
      - '9229:9229'

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - POSTGRES_HOST=postgres
      - PORT=3004
    depends_on:
      - postgres

volumes:
  postgres_data:
